Testing

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -29,3 +29,8 @@ jobs:
 
     - name: Run Tests
       run: npm test
+
+      # Add a deliberate failure step
+    - name: Deliberate failure step
+      run: exit 1
+      if: always()
